[".vim/pack/plugins/start/lightline.vim"]
    type = "archive"
    url = "https://github.com/itchyny/lightline.vim/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
